#!/usr/bin/env bash
# Auto-generated by CMake - DO NOT EDIT MANUALLY
# This script allows building without CMake installed

set -e
cd "$(dirname "$0")/libvscode-diff"

# Detect platform for library extension
if [[ "$OSTYPE" == "darwin"* ]]; then
    PLATFORM="Darwin"
    LIB_EXT="dylib"
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    PLATFORM="Linux"
    LIB_EXT="so"
else
    PLATFORM="Unknown"
    LIB_EXT="so"
fi

echo "Building vscode_diff (standalone mode)..."
echo "Compiler: /usr/bin/cc"
echo "Platform: $PLATFORM"

# Compiler and flags from CMake configuration
CC="/usr/bin/cc"
CFLAGS=" -Wall -Wextra -O2 -DNDEBUG -Iinclude -Ibuild/include -Ivendor -fPIC"
LDFLAGS="-shared -lm"

# Source files (including bundled utf8proc)
SOURCES="\
default_lines_diff_computer.c \
src/char_level.c \
src/line_level.c \
src/myers.c \
src/optimize.c \
src/sequence.c \
src/range_mapping.c \
src/string_hash_map.c \
src/utils.c \
src/print_utils.c \
src/utf8_utils.c \
vendor/utf8proc.c"

# Build
mkdir -p build
mkdir -p build/include

# Generate version.h
VERSION=$(cat ../VERSION | tr -d '[:space:]')
sed "s/@1.0.0@/$VERSION/g" include/version.h.in > build/include/version.h

echo "Compiling..."
$CC $CFLAGS $LDFLAGS -o libvscode_diff.$LIB_EXT $SOURCES

echo "Installing to plugin root..."
cp libvscode_diff.$LIB_EXT ../libvscode_diff.$LIB_EXT

echo "✓ Build successful: libvscode_diff.$LIB_EXT"
cd ..
